#!/bin/bash

# from https://willwarren.com/2014/07/03/roll-dynamic-dns-service-using-amazon-route53/

source /route53.env

if [ -z "$RECORDSET" ] ; then
    echo RECORDSET env variable not set
    exit 1
fi

if [ -z "$ZONEID" ] ; then
    echo ZONEID env variable not set
    exit 1
fi


# More advanced options below
# The Time-To-Live of this recordset
TTL=300

# Change this if you want
COMMENT="auto updating at `date`"

# Change to AAAA if using an IPv6 address
TYPE="A"

#
# ===
#

# Get the external IP address from OpenDNS (more reliable than other providers)
# IP=`dig +short myip.opendns.com @resolver1.opendns.com`
IP=$(curl -s 'https://api.ipify.org?format=text')


function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

# Get current dir
# (from http://stackoverflow.com/a/246128/920350)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IPFILE="$DIR/update-route53.ip"

if ! valid_ip $IP; then
    echo "Invalid IP address: $IP"
    exit 1
fi

# Check if the IP has changed
if [ ! -f "$IPFILE" ] ; then
    touch "$IPFILE"
fi

if grep -Fxq "$IP" "$IPFILE"; then
    # IP has not changed, nothing to do
    exit 0
else
    echo $(date)
    echo "IP has changed to $IP"

    # Fill a temp file with valid JSON
    TMPFILE=$(mktemp /tmp/temporary-file.XXXXXXXX)
    cat > ${TMPFILE} << EOF
    {
      "Comment":"$COMMENT",
      "Changes":[
        {
          "Action":"UPSERT",
          "ResourceRecordSet":{
            "ResourceRecords":[
              {
                "Value":"$IP"
              }
            ],
            "Name":"$RECORDSET",
            "Type":"$TYPE",
            "TTL":$TTL
          }
        }
      ]
    }
EOF

    # Update the Hosted Zone record
    python3 -m awscli route53 change-resource-record-sets  \
        --hosted-zone-id $ZONEID  \
        --change-batch file://"$TMPFILE"

    rm $TMPFILE
fi

# All Done - cache the IP address for next time
echo "$IP" > "$IPFILE"
